name: Server

on:
  push:
    branches:
      - master
    paths:
      - "src/server/*"

jobs:
  buildeploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: cd functions && yarn --ignore-engines install
      - name: Build
        run: yarn boom-server
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
